---
title: "OR-liquor-analysis"
author: "Rochelle Rafn"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
```


```{r}
or_sales <- read.csv('/Users/rochellerafn/RStudio_Files/liquor-analysis/OR-Liquor-Sales-Store.csv')
```

```{r}
str(or_sales)
```

```{r}
or_sales <- or_sales %>%
  mutate(Month = month.name[Month], Year = as.character(Year))

or_sales$Month = factor(or_sales$Month, levels = month.name)

head(or_sales)
```


```{r}
unique(or_sales$COUNTY)
```

```{r}
unique(or_sales$Year)
```

```{r}
or_sales %>%
 group_by(Store..) %>%
  summarise()
```

```{r}
or_sales_yearly <- or_sales %>%
  group_by(Year, Month) %>%
  summarize(sum(Total.Sales))

or_sales_yearly <- or_sales_yearly %>%
  rename("Total.Sales" = "sum(Total.Sales)")

head(or_sales_yearly)
```

```{r}
# write.csv(or_sales_yearly, '/Users/rochellerafn/RStudio_Files/liquor-analysis/or_sales_yearly.csv')
```



```{r}
# library(MetBrewer)
# install.packages("devtools")
# devtools::install_github("BlakeRMills/MetBrewer")

or_sales_yearly %>%
  filter(Year < 2023) %>%
ggplot(aes(Month, Total.Sales, group = Year, color = Year)) +
  geom_line(stat = "identity")+
  scale_y_continuous(labels = scales::comma)+
  theme(panel.background = element_blank(),
        plot.background = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_color_met_d("Klimt")+
  labs(title = "Seasonality of Oregonian's Liquor Consumption is Consistent",
       subtitle = "Total Liquor Sales in Oregon",
       y = "Total Sales (in dollars)")
```

```{r}
or_sales_yearly %>%
  filter(Year < 2023) %>%
ggplot(aes(Year, Total.Sales, fill = Year, color = Year))+
  geom_col(stat = "identity")+
  scale_y_continuous(labels = scales::comma)+
  theme(panel.background = element_blank(),
        plot.background = element_blank())+
  scale_fill_met_d("Klimt")+
  scale_color_met_d("Klimt")+
  labs(y = "Total Sales (in dollars)")
```


```{r}
or_store_sales <- or_sales %>%
  group_by(Year, Month, BusinessName) %>%
  summarize(sum(Total.Sales))

or_store_sales <- or_store_sales %>%
  rename("Total.Sales" = "sum(Total.Sales)") %>%
  arrange(desc(Total.Sales))

head(or_store_sales)
```

```{r}
or_county_sales <- or_sales %>%
  group_by(Year, Month, COUNTY) %>%
  filter(Year < 2023) %>%
  summarize(sum(Total.Sales))

or_county_sales <- or_county_sales %>%
  rename("Total.Sales" = "sum(Total.Sales)") %>%
  arrange(desc(Total.Sales))

head(or_county_sales)
```


```{r}
or_county_sales %>%
ggplot(aes(reorder(COUNTY, -Total.Sales), Total.Sales, fill = COUNTY)) +
  geom_col()+
  scale_y_continuous()+
  theme_void()+
  facet_wrap(~Year)
```

```{r}
product_sales_2020 <- readxl::read_xlsx('/Users/rochellerafn/RStudio_Files/liquor-analysis/Product-Sales-Data-CY2020.xlsx', sheet = "750 ml")

str(product_sales_2020)
```

```{r}
colnames(product_sales_2020)[4] = "Units_Sold"
colnames(product_sales_2020)[5] = "Units_Price"

str(product_sales_2020)
```


```{r}
unique(product_sales_2020$Category)
```


```{r}
product_sales_2020 <- product_sales_2020 %>%
  mutate(Total_Sales = Units_Sold * Units_Price)

head(product_sales_2020)
```


```{r}
product_total_sales_2020 <- product_sales_2020 %>%
  group_by(Category) %>%
  summarize(sum(Total_Sales))

product_total_sales_2020 <- product_total_sales_2020 %>%
  rename("Total_Sales" = "sum(Total_Sales)") %>%
  arrange(desc(Total_Sales))

product_total_sales_2020
```


```{r}
ggplot(product_total_sales_2020, aes(reorder(Category, -Total_Sales), Total_Sales, group = Category, fill = Category))+
  geom_col(stat = "identity")+
  scale_y_continuous(labels = scales::comma)+
  theme(panel.background = element_blank(),
        plot.background = element_blank(),
        legend.position = "none")+
  scale_fill_met_d("Signac")+
  labs(y = "Total Sales (in dollars)",
       x = "Liquor Type")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r}
product_total_count_2020 <- product_sales_2020 %>%
  group_by(Category) %>%
  summarize(sum(Units_Sold))

product_total_count_2020 <- product_total_count_2020 %>%
  rename("Total_Units_Sold" = "sum(Units_Sold)") %>%
  arrange(desc(Total_Units_Sold))

product_total_count_2020
```


```{r}
ggplot(product_total_count_2020, aes(reorder(Category, -Total_Units_Sold), Total_Units_Sold, group = Category, fill = Category))+
  geom_col(stat = "identity")+
  scale_y_continuous(labels = scales::comma)+
  theme(panel.background = element_blank(),
        plot.background = element_blank(),
        legend.position = "none")+
  scale_fill_met_d("Signac")+
  labs(y = "Total Units Sold",
       x = "Liquor Type")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

